name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Copy files to Azure VM and update Nginx
        env:
          VM_IP: ${{ secrets.VM_IP }}
          VM_USER: ${{ secrets.VM_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP << 'EOF'
          set -e

          # Clone or pull the latest code
          cd /tmp
          if [ -d "fullstack" ]; then
            cd fullstack
            git fetch --all
            git reset --hard origin/main
          else
            git clone https://github.com/rupesh-hub/nginx-demo-app-01.git fullstack
            cd fullstack
          fi

          # Build the frontend
          cd frontend
          npm install
          npm run build
          cd ..

          # Move the application files to /var/www/fullstack
          sudo rm -rf /var/www/fullstack/*
          sudo cp -r frontend/dist /var/www/fullstack/frontend
          sudo cp -r backend /var/www/fullstack/backend

          # Update Nginx configuration
          sudo rm -f /etc/nginx/conf.d/fullstack.conf
          sudo cp fullstack.conf /etc/nginx/conf.d/

          # Validate and reload Nginx
          sudo nginx -t
          sudo systemctl reload nginx

          # Install backend dependencies and start the server
          cd /var/www/fullstack/backend
          npm install
          PORT=3000 npm run dev &

          echo "Deployment successful!"
          EOF